### ISSUE TITLE
'element' is defined but never used and 'payload' is defined but never used

### ISSUE THREAD

**Issue by Ryuuji14** [davestewart/vue-trello-clone#5]
Hi, first off, I have to say that this is amazing! I only have a little issue, I'm trying to implement it in a project for school. And when I try to move a task to one card to another, it doesn't work, the task remains in the original card.

`  onCardDropComplete(src, trg, element, payload) {
      this.$store.commit('moveItem', [
        src.params[1],
        src.index,
        trg.params[1],
        trg.index,
      ])
    },`

This is the method where the error came from. Thanks in advance.

**Comment by davestewart** [comment]
Hey! Glad you like it.

This sounds like a linter issue.

Just remove those parameters from the handler function and it should go away:

```js
onCardDropComplete(src, trg) {
  this.$store.commit('moveItem', [ src.params[1], src.index, trg.params[1], trg.index, ])
},
```

**Comment by Ryuuji14** [comment]
That worked, thanks! Now I only have one issue, when I do hover over the tasks, the "x" doesn't appear and I can't click on them (the task, to edit the description and stuff) either. I get this error: `vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in render: "TypeError: Cannot read property 'first' of undefined`, don't know if it's because of that.

![Screenshot_9](https://user-images.githubusercontent.com/54300981/86186409-074eee80-bb07-11ea-8233-d3b65f04a8bb.png)


![Screenshot_10](https://user-images.githubusercontent.com/54300981/86206296-097e7080-bb3a-11ea-9c37-2db6595e6a44.png)

**Comment by davestewart** [comment]
OK, sounds to me like you need to review some basics, and certainly learn how to use the debugger to figure this stuff out for yourself!

Here's a basic tutorial:

- https://javascript.info/debugging-chrome

As for `Cannot read property 'first' of undefined` this is a common error.

You can decipher it as:

- Cannot read property `<some property>` of `<an object that should be defined, but isn't>`

Your job is to work out where that object is, and why it doesn't exist.

If you click the `▶` arrow after the `[Vue warn]` in the error message you posted above, the error "stack" will be shown, and you can click on the line number of the errors, and explore the live code using breakpoints (as per the tutorial above) and figure it out.

Doing a quick search in the codebase, I suspect it is here (the only reference to `first`):

https://github.com/davestewart/vue-trello-clone/blob/2cf9dbf165386ef42924a7fe544e33b30d4d8edb/src/app/views/ui/UiItemForm.vue#L88

But you should use the tools provided to get to the bottom of this yourself - you will become a better programmer!

Good luck :)

**Comment by davestewart** [comment]
Took a quick look just in case anything has changed since I published this two years ago now, and it looks like it still runs as it should.

That `errors` object is from Vee Validate 2.x, so if you have used this repo as inspiration for your own, you will need to make sure it is installed.

**Comment by Ryuuji14** [comment]
That worked, thanks for the advice!
